handyhelpers/urls.py
from django.conf import settings
from django.http import HttpResponse
from django.urls import path
from django.utils import timezone
from handyhelpers.views import action
from handyhelpers.views import htmx

if "auditlog" in settings.INSTALLED_APPS:
    from handyhelpers.views import auditlog


app_name = "handyhelpers"

urlpatterns = [
    # probes
    path("live/", lambda request: HttpResponse("live"), name="live"),
    path("ready/", lambda request: HttpResponse("ready"), name="ready"),
    path(
        "starttime/",
        lambda request: HttpResponse(f"{settings.HH_STARTTIME}"),
        name="starttime",
    ),
    path(
        "uptime/",
        lambda request: HttpResponse(f"{timezone.now() - settings.HH_STARTTIME}"),
        name="uptime",
    ),
    # action views
    path("filter_list_view", action.FilterListView.as_view(), name="filter_list_view"),
    path(
        "show_all_list_view",
        action.ShowAllListView.as_view(),
        name="show_all_list_view",
    ),
    # htmx views
    path("about", htmx.AboutProjectModalView.as_view(), name="about"),
]

if "auditlog" in settings.INSTALLED_APPS:
    urlpatterns.extend(
        [
            path(
                "get_auditlog_entries/<str:model_name>/<str:pk>/",
                auditlog.GetAuditLogEntries.as_view(),
                name="get_auditlog_entries",
            ),
            path(
                "get_auditlog_entry/<int:id>/",
                auditlog.GetAuditLogEntry.as_view(),
                name="get_auditlog_entry",
            ),
        ]
    )

handyhelpers/templates/handyhelpers/generic/bs5/generic_about.html
{% extends base_template|default:"userextensions/userextensions_base.htm" %}
{% load static %}

{% block content %}
    <div class="container-fluid mb-4 animated fadeIn">
        <h1><span class="text-primary"><b>{{ title }}: </b></span><span class="text-secondary"><small>{{ subtitle }}</small></span></h1><br/>
    </div><br/>

    <div class="container mb-4 animated fadeIn" style="animation-delay: .25s;">
        <div class="row">
            <div class="col-sm-2"><i class="far fa-address-card fa-5x text-primary"></i></div>
            <div class="col-sm-10">

                {% if version %}
                <!-- version -->
                <div class="row border-bottom border-light p-2">
                    <div class="col-sm-4">
                        <span class="text-primary"><b>Version:</b></span>
                    </div>
                    <div class="col-sm-8">
                        {{ version }}
                    </div>
                </div>
                {% endif %}

                {% if details %}
                    <!-- details -->
                    <div class="row border-bottom border-light p-2">
                        <div class="col-sm-4">
                            <span class="text-primary"><b>Details:</b></span>
                        </div>
                        <div class="col-sm-8">
                            {{ details }}
                        </div>
                    </div>
                {% endif %}

                {% if source %}
                    <!-- source -->
                    <div class="row border-bottom border-light p-2">
                        <div class="col-sm-4">
                            <span class="text-primary"><b>Source Code:</b></span>
                        </div>
                        <div class="col-sm-8">
                            {{ source }}
                        </div>
                    </div>
                {% endif %}

                {% if contact %}
                    <!-- contact -->
                    <div class="row border-bottom border-light p-2">
                        <div class="col-sm-4">
                            <span class="text-primary"><b>Contact Info:</b></span>
                        </div>
                        <div class="col-sm-8">
                            {{ contact }}
                        </div>
                    </div>
                {% endif %}

                {% if links %}
                    <!-- links -->
                    <div class="row border-bottom border-light p-2">
                        <div class="col-sm-4">
                            <span class="text-primary"><b>Links:</b></span>
                        </div>
                        <div class="col-sm-8">
                            {% for link in links %}
                            <a href="{{ link.value }}" target="_blank">{{ link.key }}</a><br/>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}

handyhelpers/templates/handyhelpers/generic/bs5/generic_action.html
{% extends base_template|default:"handyhelpers/handyhelpers_base.htm" %}
{% load static %}
{% load handyhelper_tags %}

{% block local_head %}
    <link href="{% static 'handyhelpers/css/handyhelper-cards.css' %}" rel="stylesheet">
    <link href="{% static 'handyhelpers/css/zoom-groups.css' %}" rel="stylesheet">
{% endblock local_head %}

{% block content %}
    <!-- Page header -->
    <section class="animated fadeIn">
        <header class="m-5">
            <div class="headline text-center">
                <div class="container">
                    <div class="h1 text-primary fw-bold mb-3">{{ title|safe }}</div>
                    <div class="h5 text-secondary">{{ subtitle|safe }}</div>
                </div>
            </div>
        </header>
    </section>

    <!-- Page Content -->
    <section class="animated fadeIn" style="animation-delay: .25s;">
        <div class="zoom-group-flex-container">
            <!-- unprotected items -->
            {% for item in item_list %}
                {% if item.hx_get %}
                <a href="#" hx-get="{{ item.hx_get }}" hx-target="#modal_wrapper" data-bs-toggle="modal" data-bs-target="#modal_wrapper"
                class="card zoom-card zoom-admin-card">
                {% else %}
                <a href="{{ item.url }}" class="card zoom-card zoom-admin-card">
                {% endif %}
                    <div class="icon">{{ item.icon|safe }}</div>
                    <div class="title">{{ item.title }}</div>
                </a>
            {% endfor %}

            <!-- protected items -->
            {% if request.user|has_group:protected_group_name %}
                {% for item in protected_item_list %}
                    {% if item.hx_get %}
                    <a href="#" hx-get="{{ item.hx_get }}" hx-target="#modal_wrapper" data-bs-toggle="modal" data-bs-target="#modal_wrapper"
                    class="card zoom-card zoom-admin-card">
                    {% else %}
                    <a href="{{ item.url }}" class="card zoom-card zoom-admin-card">
                    {% endif %}                        
                        <div class="icon">{{ item.icon|safe }}</div>
                        <div class="title">{{ item.title }}</div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </section>

    {% include 'handyhelpers/component/bs5/modals.htm' %}
{% endblock content %}

handyhelpers/templates/handyhelpers/generic/bs5/generic_form.htm
{% csrf_token %}
<input type="hidden" name="{{ form_name }}" value="1">
{% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        {{ form.errors }}
    </div>
{% endif %}
{% for field in form.visible_fields %}
    <div class="form-group mx-2 mt-2 mb-3">
        <div class="col-sm-12 fw-bold text-primary">
            <span id="id_{{ field.name }}_required" class="text-danger">{% if field.field.required %}*{% endif %}</span>{{ field.label_tag }}
        </div>
        <div class="col-sm-12">
            {% if field.errors %}
                <div class="alert alert-danger alert-tiny">
                    {{ field.errors }}
                </div>
            {% endif %}
            <span data-bs-toggle="tooltip" data-bs-title="{{ field.help_text }}" data-placement="right" data-container="body">
                {{ field }}
                <div class="valid-feedback" id="id_{{field.name}}_valid"></div>
                <div class="invalid-feedback" id="id_{{field.name}}_invalid"></div>
            </span>
        </div>
    </div>
{% endfor %}
{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}

handyhelpers/templates/handyhelpers/generic/bs5/generic_form_htmx_get.htm
{% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        {{ form.errors }}
    </div>
{% endif %}
{% for field in form.visible_fields %}
    <div class="form-group">
        <div class="col-sm-12">
            <span id="id_{{ field.name }}_required" class="text-danger">{% if field.field.required %}*{% endif %}</span>{{ field.label_tag }}
        </div>
        <div class="col-sm-12">
            {% if field.errors %}
                <div class="alert alert-danger alert-tiny">
                    {{ field.errors }}
                </div>
            {% endif %}
            <span data-bs-toggle="tooltip" data-bs-title="{{ field.help_text }}" data-placement="right" data-container="body">
                {{ field }}
                <div class="valid-feedback" id="id_{{field.name}}_valid"></div>
                <div class="invalid-feedback" id="id_{{field.name}}_invalid"></div>
            </span>
        </div>
    </div>
{% endfor %}
{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}

handyhelpers/templates/handyhelpers/generic/bs5/generic_index.html
{% extends base_template|default:"handyhelpers/handyhelpers_base.htm" %}
{% load static %}
{% load handyhelper_tags %}

{% block local_head %}
    <link href="{% static 'handyhelpers/css/handyhelper-cards.css' %}" rel="stylesheet">
    <link href="{% static 'handyhelpers/css/zoom-groups.css' %}" rel="stylesheet">
{% endblock local_head %}

{% block content %}
    <!-- Page header -->
    <section>
        <header class="m-5 animated fadeIn">
            <div class="headline text-center">
                <div class="container">
                    <div class="h1 text-primary fw-bold mb-3">{{ title|safe }}</div>
                    <div class="h5 text-secondary">{{ subtitle|safe }}</div>
                </div>
            </div>
        </header>

        <div class="zoom-group-flex-container animated fadeIn" style="animation-delay: .25s;">

            <!-- unprotected items -->
            {% for item in item_list %}
                <a href="{{ item.url }}" class="card zoom-card zoom-index-card">
                    <div class="icon">{{ item.icon|safe }}</div>
                    <div class="title">{{ item.title }}</div>
                    <div class="description">{{ item.description }}</div>
                </a>
            {% endfor %}

            <!-- protected items -->
            {% if request.user|has_group:protected_group_name %}
                {% for item in protected_item_list %}
                    <a href="{{ item.url }}" class="card zoom-card zoom-index-card">
                        <div class="icon">{{ item.icon|safe }}</div>
                        <div class="title">{{ item.title }}</div>
                        <div class="description">{{ item.description }}</div>
                    </a>
                {% endfor %}
            {% endif %}

        </div>
    </section>

{% endblock %}

handyhelpers/templates/handyhelpers/generic/bs5/generic_list.html
{% extends base_template|default:"handyhelpers/bs5/handyhelpers_base.htm" %}
{% load static %}
{% load handyhelper_tags %}

{% block local_head %}
<link href="{% static 'node_modules/bootstrap-table/dist/bootstrap-table.min.css' %}" rel="stylesheet">
<link href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet">
{% endblock %}

{% block local_javascript %}
<!-- bootstrap table -->
<script type="text/javascript" src="{% static 'node_modules/bootstrap-table/dist/bootstrap-table.min.js' %}"></script>
<script type="text/javascript" src="{% static 'node_modules/bootstrap-table/dist/locale/bootstrap-table-en-US.min.js' %}"></script>

<script language="JavaScript">
    function dataValueInt(a, b) {
        /* sort based on integer value in data-value attribute */
        var a_myRegexp = /(?:^|\s)data-value=\"(.*?)\"(?:\s|$)/g;
        var b_myRegexp = /(?:^|\s)data-value=\"(.*?)\"(?:\s|$)/g;
        var a = parseInt(a_myRegexp.exec(a)[1]);
        var b = parseInt(b_myRegexp.exec(b)[1]);
        if (a < b) return -1;
        if (a > b) return 1;
        return 0;
    }

    function dataValueFloat(a, b) {
        /* sort based on integer value in data-value attribute */
        var a_myRegexp = /(?:^|\s)data-value=\"(.*?)\"/g;
        var b_myRegexp = /(?:^|\s)data-value=\"(.*?)\"/g;
        var a = parseFloat(a_myRegexp.exec(a)[1]);
        var b = parseFloat(b_myRegexp.exec(b)[1]);
        if (a < b) return -1;
        if (a > b) return 1;
        return 0;
    }

</script>
{% endblock %}

{% block content %}
    {% include "handyhelpers/generic/bs5/generic_list_content.htm" %}
{% endblock content %}

handyhelpers/templates/handyhelpers/generic/bs5/generic_list_content.htm
{% load handyhelper_tags %}
<div class="container-fluid animated fadeIn my-5">
    <h1><span class="text-primary"><b>{{ title }}:</b></span> {% if subtitle %}<span class="text-secondary"><small><small>{{ subtitle }}</small></small></span>{% endif %}</h1>

    <div class="text-end">
        {# include extra_controls #}
        {% if extra_controls.items %}
        {% for name, control in extra_controls.items %}
            <a href="{{ control.url }}" title="{{ control.title }}" class="mx-1">{{ control.icon|safe }}</a>
        {% endfor %}
        {% endif %}

        {# To include a create form, exposed via modal, include create_form (dict) in the context of your view. The create_from must include modal_name and link_title fields #}
        {% if create_form %}
        {% if allow_create_groups and request.user|in_any_group:allow_create_groups %}
        <a href="#" data-bs-toggle="modal" data-bs-target="#modal_{{ create_form.modal_name }}" title="{{ create_form.tool_tip|default_if_none:'create' }}" class="mx-1">
            <i class="fas fa-plus-circle"></i>
            {% if create_form.link_title %} {{ create_form.link_title }} {% endif %}
        </a>
        {% endif %}
        {% endif %}

        {# To include a filter form, exposed via modal, include filter_form (dict) in the context of your view. The filter_from must include modal_name and link_title fields #}
        {% if filter_form %}
        <a href="#" data-bs-toggle="modal" data-bs-target="#modal_{{ filter_form.modal_name }}" title="{{ filter_form.tool_tip|default_if_none:'filter' }}" class="mx-1">
            <i class="fas fa-filter"></i>
            {% if filter_form.link_title %} {{ filter_form.link_title }} {% endif %}
        </a>
            {% if filter_form.undo and request.META.QUERY_STRING %}
            <a href="{% url 'handyhelpers:show_all_list_view' %}" title="clear filters" class="ms-1">
                <i class="fas fa-undo-alt"></i>
            </a>
            {% endif %}
        {% endif %}
    </div>

    {% include table %}
    
    {% if is_paginated_view %}
    {% include 'handyhelpers/generic/bs5/partials/pagination_controls.htm' %}
    {% endif %}

</div>

{# include classic modals if create or filter form is included #}
{# TODO: move this to htmx soon #}
{% if create_form or filter_form %}
    {% include 'handyhelpers/component/bs5/modals.htm' %}
{% endif %}

{# include generic modal form for the create object form if passed from the view #}
{% with create_form as form_data %}
    {% include 'handyhelpers/generic/bs5/generic_modal_form.htm' %}
{% endwith %}

{# include generic modal form for the filter object form if passed from the view #}
{% with filter_form as form_data %}
    {% include 'handyhelpers/generic/bs5/generic_modal_form.htm' %}
{% endwith %}

{# include custom modal html/js template if passed in from the view #}
{% if modals %}
    {% include modals %}
{% endif %}

{# block for additional static content #}
{% block additional_static %}
{% if add_static %}
{{ add_static|safe }}
{% endif %}
{% endblock additional_static %}

{# block for additional template content #}
{% block additional_template %}
{% if add_template %}
{% include add_template %}
{% endif %}
{% endblock additional_template %}

handyhelpers/templates/handyhelpers/generic/bs5/generic_modal_form.htm
<!-- {{ form_data.modal_name }} Form -->
<div class="modal fade" id="modal_{{ form_data.modal_name }}" {% if form_data.modal_backdrop %}data-backdrop="{{ form_data.modal_backdrop }}"{% endif %} role="dialog" aria-labelledby="modal_{{ form_data.modal_name }}_label" aria-hidden="true">
    <div class="modal-dialog {% if form_data.modal_scrollable %}modal-dialog-scrollable{% endif %} {% if form_data.modal_size %}{{ form_data.modal_size }}{% endif %}" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-primary" id="modal_{{ form_data.modal_name }}_label">{{ form_data.title|safe }}</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="id_modal_{{ form_data.modal_name }}_form_body">
                <form {% if form_data.form %} enctype="multipart/form-data" {% endif %} id="form_{{ form_data.modal_name }}" class="form-horizontal" action="{{ form_data.action_url }}" method="POST"
                      {% if form_data.autocomplete %}autocomplete="{{ form_data.autocomplete }}"{% endif %}>

                    {% with form_data.form as form %}
                        {% include 'handyhelpers/generic/bs5/generic_form.htm' %}
                    {% endwith %}
                <div class="text-end mt-4 mx-2 my-3">
                    <button type="button" class="me-1 btn btn-light" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="ms-1 btn btn-primary" id="id_{{ form_data.modal_name }}_submit">{{ form_data.action }}</button>
                </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

handyhelpers/templates/handyhelpers/generic/bs5/generic_modal_form_htmx.htm
<!-- {{ form_data.modal_name }} Form -->
<div class="modal fade" id="modal_{{ form_data.modal_name }}" {% if form_data.modal_backdrop %}data-backdrop="{{ form_data.modal_backdrop }}"{% endif %} role="dialog" aria-labelledby="modal_{{ form_data.modal_name }}_label" aria-hidden="true">
    <div class="modal-dialog {% if form_data.modal_scrollable %}modal-dialog-scrollable{% endif %} {% if form_data.modal_size %}{{ form_data.modal_size }}{% endif %}" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modal_{{ form_data.modal_name }}_label">{{ form_data.modal_title|safe }}</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="id_modal_{{ form_data.modal_name }}_form_body">
                <form {% if form_data.form %} enctype="multipart/form-data" {% endif %} id="form_{{ form_data.modal_name }}" class="form-horizontal" {{ form_data.hx_method }}="{{ form_data.hx_url }}" hx-target="#{{ form_data.hx_target }}" method="{{ form_data.method }}"
                      {% if form_data.autocomplete %}autocomplete="{{ form_data.autocomplete }}"{% endif %}>
                    {% with form_data.form as form %}
                        {% include 'handyhelpers/generic/bs5/generic_form_htmx_get.htm' %}
                    {% endwith %}
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                    <!-- Submit Button-->
                    <button type="submit" class="btn btn-primary" id="id_{{ form_data.modal_name }}_submit" data-bs-dismiss="modal">{{ form_data.action }}</button>
                </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

handyhelpers/templates/handyhelpers/generic/bs5/generic_modal_form_wide.htm
<!-- {{ form_data.modal_name }} Form -->
<div class="modal fade" id="modal_{{ form_data.modal_name }}" {% if form_data.modal_backdrop %}data-backdrop="{{ form_data.modal_backdrop }}"{% endif %} role="dialog" aria-labelledby="modal_{{ form_data.modal_name }}_label" aria-hidden="true">
    <div class="modal-dialog {% if form_data.modal_size %}{{ form_data.modal_size }}{% endif %}">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modal_{{ form_data.modal_name }}_label">{{ form_data.title|safe }}</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {% if form_selector %}
                <div class="modal-body">
                    {{ form_selector }}
                </div>
            {% endif %}

            <form {% if form_data.form %} enctype="multipart/form-data" {% endif %} id="form_{{ form_data.modal_name }}" class="form-horizontal" action="{{ form_data.action_url }}" method="POST"
                  {% if form_data.autocomplete %}autocomplete="{{ form_data.autocomplete }}"{% endif %}">
                <div class="modal-body" id="id_modal_{{ form_data.modal_name }}_form_body">
                    {% with form_data.form as form %}
                        {% include 'handyhelpers/generic/generic_form_wide.htm' %}
                    {% endwith %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                    <!-- Submit Button-->
                    <button type="submit" class="btn btn-primary">{{ form_data.action }}</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->